/*  Declaration of the ISftpProvider and ISftpConsumer interfaces.

    Copyright (C) 2008  Alexander Lamaison <awl03@doc.ic.ac.uk>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

//#include "stdafx.h"
//#include "resource.h"       // main symbols

import "unknwn.idl";

/**
 * The record structure returned by the GetListing() method of the SFTPProvider.
 *
 * This structure represents a single file contained in the directory 
 * specified to GetListing().
 */
struct Listing {
	BSTR bstrFilename;    ///< Directory-relative filename (e.g. README.txt)
	ULONG uPermissions;   ///< Unix file permissions
	BSTR bstrOwner;       ///< The user name of the file's owner
	BSTR bstrGroup;       ///< The name of the group to which the file belongs
	ULONG uSize;          ///< The file's size in bytes
	ULONG cHardLinks;     ///< The number of hard links referencing this file
	DATE dateModified;    ///< The date and time at which the file was 
	                      ///< last modified in automation-compatible format
};

// IEnumListing
[
	object, uuid("b816a843-5022-11dc-9153-0090f5284f85"),
	oleautomation,
	helpstring("IEnumListing Interface"),
	//pointer_default(unique)
]
interface IEnumListing : IUnknown
{
	/* Will need local/remote hack if used remotely */
	HRESULT Next (
		[in] ULONG celt,
		[out] struct Listing *rgelt,
		[out] ULONG *pceltFetched);
	HRESULT Skip ([in] ULONG celt);
	HRESULT Reset ();
	HRESULT Clone ([out] IEnumListing **ppEnum);
};

// ISftpConsumer
[
	object, uuid("DBEC732D-0B2A-4c52-ACED-89A2C2C27675"),
	//uuid("b816a844-5022-11dc-9153-0090f5284f85"),
	oleautomation, 
	helpstring("ISftpConsumer Interface"),
	//pointer_default(unique)
]
interface ISftpConsumer : IUnknown
{
	HRESULT OnPasswordRequest(
		[in]          BSTR bstrRequest,
		[out, retval] BSTR *pbstrPassword
	);
	HRESULT OnYesNoCancel(
		[in]          BSTR bstrMessage,
		[in]          BSTR bstrYesInfo,
		[in]          BSTR bstrNoInfo,
		[in]          BSTR bstrCancelInfo,
		[in]          BSTR bstrTitle,
		[out, retval] int *pnResult
	);
	HRESULT OnConfirmOverwrite(
		[in]          BSTR bstrOldFile,
		[in]          BSTR bstrExistingFile
	);
	HRESULT OnConfirmOverwriteEx(
		[in]          struct Listing ltOldFile,
		[in]          struct Listing ltExistingFile
	);
	HRESULT OnReportError(
		[in]          BSTR bstrMessage
	);
};

// ISftpProvider
[
	object, uuid("356BE07D-6413-4290-96D1-4404AA1DC57E"),
	//uuid("b816a841-5022-11dc-9153-0090f5284f85"),
	oleautomation,
	helpstring("ISftpProvider Interface"),
	//pointer_default(unique)
]
interface ISftpProvider : IUnknown
{
	HRESULT Initialize(
		[in] ISftpConsumer *pConsumer,
		[in] BSTR bstrUser,
		[in] BSTR bstrHost,
		[in] UINT uPort
	);
	HRESULT GetListing(
		[in] BSTR bstrDirectory,
		[out, retval] IEnumListing **ppEnum
	);
	HRESULT Rename(
		[in] BSTR bstrFromFilename,
		[in] BSTR bstrToFilename,
		[out, retval] VARIANT_BOOL *fWasTargetOverwritten
	);
};
