import "oaidl.idl";
import "ocidl.idl";

[
	uuid(b816a861-5022-11dc-9153-0090f5284f85),
	version(1.0),
	helpstring("Provider 1.0 Type Library")
]
library ProviderLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(b816a862-5022-11dc-9153-0090f5284f85),
		helpstring("Provider Component")
	]
	coclass Provider
	{
		[default] interface IUnknown;
	};

	[
		uuid(b816a863-5022-11dc-9153-0090f5284f85),
		helpstring("RealDispenser Component")
	]
	coclass RealDispenser
	{
		[default] interface IOleItemContainer;
	};

	[
		uuid(b816a864-5022-11dc-9153-0090f5284f85),
		helpstring("Dispenser Component")
	]
	coclass Dispenser
	{
		[default] interface IOleItemContainer;
	};
};
